
'use server';

/**
 * @fileOverview Analyzes all customer profiles to generate high-level predictive analytics and trends.
 *
 * - generateAnalyticsInsights - The main flow function.
 * - GenerateAnalyticsInsightsOutput - The structured output for the analytics dashboard.
 */

import { ai } from '@/ai/genkit';
import { z } from 'zod';
import dbConnect from '@/lib/mongoose';
import CustomerProfile from '@/models/customer-profile';
import Story from '@/models/story';

const PredictionSchema = z.object({
  segmentDescription: z.string().describe("A description of the customer segment this prediction applies to."),
  prediction: z.string().describe("The specific prediction for this segment (e.g., 'Likely to purchase premium products in the next quarter')."),
  confidenceScore: z.number().describe("Confidence score (0-100) for this prediction."),
  recommendation: z.string().describe("An actionable recommendation based on this prediction."),
});

const TrendSchema = z.object({
  trend: z.string().describe("A description of the identified trend (e.g., 'Rising interest in sustainable travel')."),
  supportingData: z.string().describe("A brief summary of the data points supporting this trend."),
  implication: z.string().describe("The business implication of this trend."),
});

const SeasonalForecastSchema = z.object({
    season: z.string().describe("The season or event for the forecast (e.g., 'Summer', 'Back-to-School', 'Holiday Season')."),
    segmentDescription: z.string().describe("The customer segment the forecast applies to."),
    predictedBehavior: z.string().describe("The predicted behavior for this segment during the season."),
    recommendation: z.string().describe("A marketing recommendation based on this seasonal forecast."),
});

const InterestTrendSchema = z.object({
    interest: z.string().describe("The cultural interest or preference (e.g., 'Indie Music', 'Vintage Fashion')."),
    changeDescription: z.string().describe("A brief explanation of why this trend is emerging or declining."),
});

const CulturalShiftStorySchema = z.object({
    title: z.string().describe("A catchy, narrative headline for the most significant cultural shift detected (e.g., 'The Rise of the Mindful Hedonist')."),
    narrative: z.string().describe("A 2-3 paragraph story explaining this cultural shift. It should synthesize multiple data points into a cohesive narrative about what's changing in the customer base and why. This is an automated hypothesis generated by the AI."),
    keyDataPoints: z.array(z.string()).describe("A list of 3-4 specific data points or trends that support this story."),
    recommendation: z.string().describe("A single, powerful strategic recommendation on how the business can capitalize on this cultural shift."),
});

const GenerateAnalyticsInsightsOutputSchema = z.object({
  overallSummary: z.string().describe("A high-level summary of the most important findings from the analysis."),
  keyPatterns: z.array(z.string()).describe("List of 3-5 key behavioral or cultural patterns identified across the entire customer base. This is part of the AI's self-learning pattern discovery."),
  predictions: z.object({
    purchaseLikelihood: PredictionSchema,
    churnRisk: PredictionSchema,
    brandAdvocacy: PredictionSchema,
    upsellOpportunity: PredictionSchema,
  }),
  topEmergingInterests: z.array(InterestTrendSchema).length(5).describe("A ranked list of the top 5 emerging cultural interests gaining popularity."),
  topDecliningInterests: z.array(InterestTrendSchema).length(5).describe("A ranked list of the top 5 declining cultural interests losing engagement."),
  seasonalForecasts: z.array(SeasonalForecastSchema).describe("2-3 seasonal behavior forecasts for key customer segments."),
  marketOpportunityGaps: z.array(z.string()).describe("A list of 2-3 potential market opportunity gaps based on unmet or underserved cultural preferences in the data."),
  competitiveIntelligence: z.string().describe("A brief analysis of how the identified trends position the business against potential competitors and where cultural gaps can be turned into a competitive advantage."),
  dataShiftAlert: z.string().optional().describe("An alert for cultural anomaly detection. Populate this with a concise message if a significant, rapid shift in customer data patterns is detected (e.g., a trend rapidly growing to affect >15% of the base). Omit this field entirely if no significant shifts are detected."),
  culturalShiftStory: CulturalShiftStorySchema.describe("A narrative story about the single most important cultural shift detected in the data. This is the AI's automated hypothesis generation at work."),
});

export type GenerateAnalyticsInsightsOutput = z.infer<typeof GenerateAnalyticsInsightsOutputSchema>;

export async function generateAnalyticsInsights(): Promise<GenerateAnalyticsInsightsOutput> {
  return generateAnalyticsInsightsFlow();
}

const analyticsPrompt = ai.definePrompt({
  name: 'analyticsInsightsPrompt',
  input: { schema: z.any() }, // Input is the array of profiles
  output: { schema: GenerateAnalyticsInsightsOutputSchema },
  prompt: `You are a world-class, self-learning cultural sociologist and market intelligence analyst, acting as a multi-modal analysis engine. Your task is to analyze a database of anonymized customer cultural profiles to generate a comprehensive trend report and predictive analysis. Assume the data is chronological.

Analyze the following customer profiles, inferring multi-modal context (e.g., review sentiment, browsing behavior, purchase timing patterns) where appropriate:
{{{json profiles}}}

Based on this entire dataset, perform the following self-learning analysis:
1.  **Overall Summary**: Provide a high-level summary of the most critical insights a marketing director would need to know.
2.  **Cultural Pattern Discovery**: Find 3-5 of the most significant recurring cultural patterns, synthesizing behavioral data with cultural affinities. This is a core self-learning task.
3.  **Predictive Cultural Journey Mapping**: This is crucial. Analyze the customer base to model cultural evolution. This involves predicting lifecycle transitions and identifying intervention points.
    -   **Purchase Likelihood**: Who is most likely to buy soon? What's the recommended action?
    -   **Cultural Churn Risk**: Identify segments whose cultural tastes are evolving away from our current offerings. This is your cultural churn risk classifier. What's the recommended intervention?
    -   **Brand Advocacy**: Who is most likely to become a vocal supporter of the brand?
    -   **Cultural Upsell Opportunity**: Identify segments whose evolving tastes make them prime candidates for new or different product categories. This is your culture-aligned upsell product matcher. What is the recommended product or service to offer?
4.  **Cultural Trend Monitoring**:
    -   **Top 5 Emerging Interests**: Identify the top 5 cultural interests that are gaining popularity. Consider what external trends might be influencing this.
    -   **Top 5 Declining Interests**: Identify the top 5 cultural interests that are losing engagement.
5.  **Seasonal Behavior Forecasts**: Predict behavior for 2-3 key segments during upcoming seasons, considering how their cultural tastes might influence holiday or event-based purchasing. This helps identify intervention points.
6.  **Market Intelligence & Product Development Insights**:
    -   **Market Opportunity Gaps**: Based on the analysis, perform a cultural gap analysis to identify 2-3 potential market opportunities where customer preferences appear to be underserved. This should guide future product development.
    -   **Competitive Intelligence**: Provide a brief analysis of how these trends could create a competitive advantage. What cultural positioning should the business take?
7.  **Cultural Anomaly Detection**: Determine if there are any recent, significant, and rapid shifts in the overall data patterns (e.g., a single trend growing to affect >15% of the customer base). If so, generate a concise alert message for the 'dataShiftAlert' field. If not, omit this field. This is a key self-learning capability.
8.  **Automated Hypothesis Generation (Cultural Shift Story)**: This is the most important part of your self-learning analysis. Synthesize all your findings to identify the SINGLE most significant, interesting, or surprising cultural shift occurring in the data. Create a compelling narrative story about it, complete with a title, a short narrative explaining your hypothesis, the key data points supporting it, and a powerful recommendation.

Synthesize all of this into the specified JSON format to power a trend monitoring dashboard.
`,
});

const generateAnalyticsInsightsFlow = ai.defineFlow(
  {
    name: 'generateAnalyticsInsightsFlow',
    outputSchema: GenerateAnalyticsInsightsOutputSchema,
  },
  async () => {
    await dbConnect();
    const profiles = await CustomerProfile.find({}).lean();

    const MAX_PROFILES_FOR_FULL_ANALYSIS = 100;
    let profilesForPrompt;
    if (profiles.length > MAX_PROFILES_FOR_FULL_ANALYSIS) {
        // Create a summary of profiles if there are too many
        profilesForPrompt = profiles.slice(0, MAX_PROFILES_FOR_FULL_ANALYSIS).map(p => ({
            ageRange: p.ageRange,
            spendingLevel: p.spendingLevel,
            interactionFrequency: p.interactionFrequency,
            culturalDNA: p.culturalDNA ? {
                music: p.culturalDNA.music.score,
                entertainment: p.culturalDNA.entertainment.score,
                dining: p.culturalDNA.dining.score,
                fashion: p.culturalDNA.fashion.score,
                travel: p.culturalDNA.travel.score,
                socialCauses: p.culturalDNA.socialCauses.score,
            } : {}
        }));
    } else {
        profilesForPrompt = profiles.map(p => ({
            ageRange: p.ageRange,
            spendingLevel: p.spendingLevel,
            interactionFrequency: p.interactionFrequency,
            culturalDNA: p.culturalDNA,
        }));
    }


    const { output } = await analyticsPrompt({ profiles: profilesForPrompt });

    if (!output) {
      throw new Error('The AI model did not return a valid analytics report.');
    }

    // Save the story to the database for historical tracking
    await Story.create(output.culturalShiftStory);
    
    return output;
  }
);
